import = [
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
]

[cursor]
style = "Block"

[font]
size = 12.0

[font.bold]
family = "Comic Shanns Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Comic Shanns Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Comic Shanns Nerd Font"
style = "Italic"

[font.normal]
family = "Comic Shanns Nerd Font"
style = "Regular"

[window]
decorations = "full"
opacity = 1.0

[window.padding]
x = 10
y = 10
